INSERT IGNORE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES 
(1, 50, 0, '', '', 'Deprecated quest: Sweet Amber'),
(1, 53, 0, '', '', 'Deprecated quest: Sweet Amber'),
(1, 12764, 0, '', '', 'Deprecated quest: The Secret to Kungaloosh'),
(1, 160, 0, '', '', 'Deprecated quest: Note to the Mayor'),
(1, 252, 0, '', '', 'Deprecated quest: Translation to Ello'),
(1, 79, 0, '', '', 'Deprecated quest: The Legend of Stalvan'),
(1, 97, 0, '', '', 'Deprecated quest: The Legend of Stalvan'),
(1, 227, 0, '', '', 'Deprecated quest: Morgan Ladimore'),
(1, 80, 0, '', '', 'Deprecated quest: The Legend of Stalvan'),
(1, 265, 0, '', '', 'Deprecated quest: The Shadowy Search Continues'),
(1, 251, 0, '', '', 'Deprecated quest: Translate Abercrombie\'s Note'),
(1, 266, 0, '', '', 'Deprecated quest: Inquire at the Inn'),
(1, 75, 0, '', '', 'Deprecated quest: The Legend of Stalvan'),
(1, 34112, 0, '', '', 'Deprecated quest: Rest and Relaxation'),
(1, 268, 0, '', '', 'Deprecated quest: Return to Sven'),
(1, 394, 0, '', '', 'Deprecated quest: The Head of the Beast'),
(1, 4186, 0, '', '', 'Deprecated quest: The True Masters'),
(1, 331, 0, '', '', 'Deprecated quest: Report to Doren'),
(1, 1242, 0, '', '', 'Deprecated quest: The Missing Diplomat'),
(1, 229, 0, '', '', 'Deprecated quest: The Daughter Who Lived'),
(1, 223, 0, '', '', 'Deprecated quest: Worgen in the Woods'),
(1, 1043, 0, '', '', 'Deprecated quest: The Scythe of Elune'),
(1, 27723, 0, '', '', 'Deprecated quest: Kyle\'s Test Quest'),
(1, 31143, 0, '', '', 'Deprecated quest: Join the Battle!'),
(1, 31144, 0, '', '', 'Deprecated quest: They Sent Assassins'),
(1, 3112, 0, '', '', 'Deprecated quest: Simple Memorandum'),
(1, 3113, 0, '', '', 'Deprecated quest: Encrypted Memorandum'),
(1, 7638, 0, '', '', 'Deprecated quest: Lord Grayson Shadowbreaker'),
(1, 7646, 0, '', '', 'Deprecated quest: The Divination Scryer'),
(1, 63447, 0, '', '', 'Deprecated quest: Fear No Evil'),
(1, 25117, 0, '', '', 'Deprecated quest: Scout\'s Dishonor'),
(1, 26155, 0, '', '', 'Deprecated quest: A Dark Threat, Remembered'),
(1, 26156, 0, '', '', 'Deprecated quest: All The King\'s Men'),
(1, 327, 0, '', '', 'UNUSED'),
(1, 260, 0, '', '', 'UNUSED'),
(1, 25119, 0, '', '', 'Deprecated quest: Impulse Hunting'),
(1, 531, 0, '', '', 'Deprecated quest: Vyrin\'s Revenge'),
(1, 526, 0, '', '', 'Deprecated quest: Lightforge Ingots'),
(1, 5626, 0, '', '', 'Deprecated quest: In Favor of the Light'),
(1, 6064, 0, '', '', 'Deprecated quest: Taming the Beast'),
(1, 6074, 0, '', '', 'Deprecated quest: The Hunter\'s Path'),
(1, 6075, 0, '', '', 'Deprecated quest: The Hunter\'s Path'),
(1, 6076, 0, '', '', 'Deprecated quest: The Hunter\'s Path'),
(1, 6084, 0, '', '', 'Deprecated quest: Taming the Beast'),
(1, 6085, 0, '', '', 'Deprecated quest: Taming the Beast'),
(1, 316, 0, '', '', 'UNUSED'),
(1, 1700, 0, '', '', 'Deprecated quest: Grimand Elmore');
